# this is the spark-worker dockerfile

FROM glorysdj/sparkbase:0.1

MAINTAINER glorysdj glorysdj@gmail.com

EXPOSE 7078
EXPOSE 8081

#ADD ./run.sh /opt/
#RUN chmod 777 /opt/run.sh
#ENTRYPOINT $SPARK_HOME/bin/spark-class org.apache.spark.deploy.worker.Worker spark://10.239.157.101:49153 && /bin/bash
