# this is the first dockerfileFROM ubuntu:14.04

ADD ./apt.conf /etc/apt/
RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list

# Upgrade package index
RUN apt-get update
# install a few other useful packages plus Open Jdk 7
RUN apt-get install -y less nano 
