# this is the first dockerfile

FROM ubuntu:precise

ADD ./apt.conf /etc/apt/
RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list

# Upgrade package index
RUN apt-get update
# install a few other useful packages plus Open Jdk 7
RUN apt-get install -y sudo nano 
